package com.aatlas.suppliers.internal;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Instant;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * {@link RiskScoring} against real, hand-picked inputs - no hashing anywhere in the class
 * under test, so every assertion here pins an actual formula result rather than a golden
 * fixture generated by the same code it checks.
 */
class RiskScoringTest {

    private static final Instant NOW = Instant.parse("2026-09-01T00:00:00Z");

    @Test
    @DisplayName("not assessed: neither an observed nor a provided otif or defect rate scores nothing")
    void notAssessedWhenBothOtifAndDefectAreAbsent() {
        RiskScoring.Input input =
                new RiskScoring.Input(false, null, null, null, null, null, null, "Medium", 100.0);

        SupplierRisk risk = RiskScoring.supplierRisk(input, null, NOW);

        assertThat(risk.score()).isNull();
        assertThat(risk.level()).isNull();
        assertThat(risk.consistency()).isNull();
        assertThat(risk.trend()).isNull();
        assertThat(risk.factors()).isEmpty();
        assertThat(risk.computedAt()).isEqualTo(NOW);
    }

    @Test
    @DisplayName("provided-only: fewer than five received orders means variance, consistency, trend and delay stay null")
    void providedOnlyIgnoresObservedDimensions() {
        // otif 90, defect 1.0: score = (100-90)*1.7 + 1.0*2.5 = 17 + 2.5 = 19.5 -> round 20, Low.
        RiskScoring.Input input = new RiskScoring.Input(false, 90.0, 1.0, null, null, null, null, null, null);

        SupplierRisk risk = RiskScoring.supplierRisk(input, null, NOW);

        assertThat(risk.score()).isEqualTo(20);
        assertThat(risk.level()).isEqualTo("Low");
        assertThat(risk.consistency()).isNull();
        assertThat(risk.trend()).isNull();
        assertThat(risk.recentDelayPct()).isNull();
        assertThat(risk.leadVarianceDays()).isNull();
        assertThat(risk.factors()).extracting(RiskFactor::label)
                .containsExactly("On-time fulfilment", "Historical delay");
    }

    @Test
    @DisplayName("provided-only still applies a supplied capacity term")
    void providedOnlyCanStillFlagCapacity() {
        RiskScoring.Input input = new RiskScoring.Input(false, 95.0, 0.5, null, null, null, null, "Low", 900.0);

        SupplierRisk risk = RiskScoring.supplierRisk(input, null, NOW);

        // (100-95)*1.7 + 12 (Low capacity) + 0.5*2.5 = 8.5 + 12 + 1.25 = 21.75 -> round 22.
        assertThat(risk.score()).isEqualTo(22);
        assertThat(risk.capacity()).isEqualTo("Low");
        assertThat(risk.factors()).extracting(RiskFactor::label).contains("Capacity");
    }

    @Test
    @DisplayName("observed: lead-time variance, trend and recent delay all feed the score and the factor list")
    void observedUsesEveryDimension() {
        // ratio = leadSd/leadAvg = 2/20 = 0.1 -> High consistency (< 0.12).
        RiskScoring.Input input = new RiskScoring.Input(
                true, 85.0, 1.0, 20.0, 2.0, "Worsening", 12.0, "Medium", 5000.0);
        RiskScoring.RatingSummary rating = new RiskScoring.RatingSummary(4.6, 12);

        SupplierRisk risk = RiskScoring.supplierRisk(input, rating, NOW);

        assertThat(risk.consistency()).isEqualTo("High");
        assertThat(risk.trend()).isEqualTo("Worsening");
        assertThat(risk.recentDelayPct()).isEqualTo(12.0);
        assertThat(risk.leadVarianceDays()).isEqualTo(2.0);
        // (100-85)*1.7 + 0.1*60 + 4 (Medium capacity) + 10 (Worsening) + 1.0*2.5
        //   = 25.5 + 6 + 4 + 10 + 2.5 = 48 -> Medium (35 <= score < 60).
        assertThat(risk.score()).isEqualTo(48);
        assertThat(risk.level()).isEqualTo("Medium");
        assertThat(risk.factors()).extracting(RiskFactor::label)
                .contains("On-time fulfilment", "Historical delay", "Capacity", "Lead-time consistency",
                        "Recent performance", "Buyer rating");
    }

    @Test
    @DisplayName("observed with a stable, improving trend applies the improving discount, not the worsening penalty")
    void improvingTrendLowersTheScore() {
        RiskScoring.Input input =
                new RiskScoring.Input(true, 97.0, 0.2, 10.0, 0.5, "Improving", -3.0, "High", 100.0);

        SupplierRisk risk = RiskScoring.supplierRisk(input, null, NOW);

        // ratio = 0.5/10 = 0.05 -> High consistency; (100-97)*1.7 + 0.05*60 + 0 (High capacity)
        //   - 4 (Improving) + 0.2*2.5 = 5.1 + 3 + 0 - 4 + 0.5 = 4.6 -> round 5, clamp floor 3 -> 5, Low.
        assertThat(risk.score()).isEqualTo(5);
        assertThat(risk.level()).isEqualTo("Low");
        assertThat(risk.trend()).isEqualTo("Improving");
    }

    @Test
    @DisplayName("score never drops below the floor of 3 or rises past the ceiling of 95")
    void scoreIsClamped() {
        RiskScoring.Input worstCase =
                new RiskScoring.Input(true, 20.0, 100.0, 50.0, 30.0, "Worsening", 80.0, "Low", 5000.0);
        RiskScoring.Input bestCase =
                new RiskScoring.Input(true, 99.0, 0.0, 7.0, 0.1, "Improving", -10.0, "High", 10.0);

        assertThat(RiskScoring.supplierRisk(worstCase, null, NOW).score()).isEqualTo(95);
        assertThat(RiskScoring.supplierRisk(bestCase, null, NOW).score()).isEqualTo(3);
    }
}
