package com.aatlas.buy.internal;

import com.aatlas.common.tenant.TenantContext;
import java.util.List;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Read-only access to the tenant's supplier panel: id, name, country, lead time, on-time
 * record and price index - the facts {@code buildBuyRecommendation} quotes every supplier
 * on.
 *
 * <p>The {@code suppliers} module (wave 1) already has this data in its {@code suppliers}
 * table, seeded from the same {@code seed/suppliers.json} used across the frontend and the
 * backend, but its only public (package-root) type is {@code SupplierPanelSeeder} - a
 * writer for seeding, not a reader. So, exactly as {@link CatalogGateway} does for
 * {@code catalog}, this reads the real {@code suppliers} table directly with plain SQL: the
 * live per-tenant panel (seeded eight plus anything added by a lookup), not a re-derivation
 * of the seeding arithmetic and not the static seed file.
 *
 * <p>TODO(merge): replace with a public reader on {@code suppliers} (e.g. a
 * {@code SupplierReader} in its package root) once one exists, and delete this class.
 */
@Component
public class SupplierGateway {

    private final JdbcTemplate jdbc;

    SupplierGateway(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /**
     * {@code SupplierRecord}'s buy-relevant fields: the ones {@code buildBuyRecommendation}
     * quotes on.
     *
     * <p>{@code defectPct} is read from the row rather than re-derived. For a seeded
     * supplier the two agree - {@code seed/suppliers.json}'s {@code defectPct} was itself
     * generated by {@code SupplierScoring.seededDefect}, so hashing the id gave the same
     * answer - but for a supplier imported from a CSV it is the reject rate the file
     * actually carried, and hashing the id would quietly discard it.
     */
    public record SupplierRow(
            String id, String name, String country, int leadTimeDays, double otifPct, double priceIndex,
            double defectPct) {
    }

    private static final String PANEL_COLUMNS =
            "supplier_key, name, country, lead_time_days, otif_pct, price_index, defect_pct";

    private static SupplierRow row(java.sql.ResultSet rs) throws java.sql.SQLException {
        return new SupplierRow(
                rs.getString("supplier_key"), rs.getString("name"), rs.getString("country"),
                rs.getInt("lead_time_days"), rs.getDouble("otif_pct"), rs.getDouble("price_index"),
                rs.getDouble("defect_pct"));
    }

    /** The whole panel: the seeded eight plus anything added from a lookup. */
    public List<SupplierRow> panel() {
        UUID tenantId = TenantContext.requireTenantId();
        return jdbc.query(
                "select " + PANEL_COLUMNS + " from suppliers where tenant_id = ? order by supplier_key",
                (rs, i) -> row(rs), tenantId);
    }

    /**
     * The suppliers that can quote on one item.
     *
     * <p>Reads {@code supplier_products} (V21), the relation that records which suppliers
     * carry which product, and takes the pair's own lead time in preference to the
     * supplier's general one - a supplier who stocks an item ships it faster than their
     * catalogue average, and that is a fact about the pair, not about either side.
     *
     * <p><b>An item with no links falls back to the whole panel.</b> The seeded sample
     * dataset links every supplier to every product, so this reproduces exactly what the
     * panel returned before V21, and the golden files the buy engines are pinned against
     * stay valid. The fallback also means a product that arrives from an import before
     * anyone has said who supplies it still costs, rather than 404ing on an empty panel.
     * The consequence worth knowing: "no links recorded" and "nobody supplies this" are the
     * same state, so narrowing an item is done by adding links to the ones that do.
     */
    public List<SupplierRow> panelFor(String itemNumber) {
        UUID tenantId = TenantContext.requireTenantId();
        List<SupplierRow> linked = jdbc.query("""
                select s.supplier_key, s.name, s.country,
                       coalesce(sp.lead_time_days, s.lead_time_days) as lead_time_days,
                       s.otif_pct, s.price_index, s.defect_pct
                from supplier_products sp
                join suppliers s on s.id = sp.supplier_id
                join products  p on p.id = sp.product_id
                where sp.tenant_id = ? and p.item_number = ?
                order by s.supplier_key
                """,
                (rs, i) -> row(rs), tenantId, itemNumber);
        return linked.isEmpty() ? panel() : linked;
    }
}
